name: ドラフトコンテンツを公開(draftsをmainにスカッシュして自動でFastFowardする)
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  reset-drafts:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'drafts' && contains(github.event.pull_request.labels.*.name, 'content-published')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Reset drafts branch to main
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout drafts
          git reset --hard main
          git push --force origin drafts